# Generated by Django 2.0.2 on 2018-03-03 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2018, 3, 3, 9, 30, 8, 310261))),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
