# Generated by Django 2.0.2 on 2018-03-03 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180303_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 3, 3, 10, 44, 55, 115591, tzinfo=utc)),
        ),
    ]
